workflows:
    android-app:
        name: Android App
        max_build_duration: 120
        #instance_type: mac_mini
        triggering:
            events:
                - push
                - tag
                - pull_request
        scripts:
            - ./gradlew assembleDebug
        artifacts:
            - build/outputs/**/**/*.apk
        publishing:
            email:
                recipients:
                    - manimv1268@gmail.com
                notify:
                  success: true
                  failure: false      